### PR TITLE
fix comparison to work with 0.21

### LINKED ISSUE #149: Wrong answer for 2D example in docs
```
julia> h(x) = sin(x[1]) - cos(x[2]) - sin(x[1]) * cos(x[1])
h (generic function with 1 method)

julia> Dh = IntervalBox(-5..5, -5..5)
[-5.0, 5.0]²

julia> Rh = enclose(h, Dh, BranchAndBoundEnclosure())
[-0.970576, 0.403252]
```
This is different from what's in the docs and is completely wrong.

```

(@v1.9) pkg> st
Status `~/.julia/environments/v1.9/Project.toml`
⌃ [79e6a3ab] Adapt v3.6.2
  [6e4b80f9] BenchmarkTools v1.3.2
  [5789e2e9] FileIO v1.16.1
  [fb4d412d] FixedPointDecimals v0.4.3
  [e9467ef8] GLMakie v0.8.11
  [2cbf6e9d] HardSphereDynamics v0.1.3 `~/Dropbox/packages/HardSphereDynamics`
  [d1acc4aa] IntervalArithmetic v0.21.2
  [ee78f7c6] Makie v0.19.11
  [5fb14364] OhMyREPL v0.5.23
  [91a5bcdd] Plots v1.39.0
⌃ [c3e4b0f8] Pluto v0.19.29
  [9c30249a] RAI v0.2.8
  [1b4d18b6] RangeEnclosures v0.2.2
⌃ [295af30f] Revise v3.5.6
  [90137ffa] StaticArrays v1.6.5
⌅ [2913bbd2] StatsBase v0.33.21
```

Version info:
```
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
```

### PR DESCRIPTION
**Pull request by lucaferranti**
now I get

```julia
(RangeEnclosures) pkg> st
Project RangeEnclosures v0.2.2
Status `~/.julia/dev/RangeEnclosures/Project.toml`
  [f6369f11] ForwardDiff v0.10.36
  [d1acc4aa] IntervalArithmetic v0.21.2
  [379f33d0] ReachabilityBase v0.2.0
  [ae029012] Requires v1.3.0

julia> h(x) = sin(x[1]) - cos(x[2]) - sin(x[1]) * cos(x[1])
h (generic function with 1 method)

julia> Dh = IntervalBox(-5 .. 5, -5 .. 5)
[-5.0, 5.0]²

julia> res = enclose(h, Dh, BranchAndBoundEnclosure())
[-2.71068, 2.71313]
```

fixes #149

### CODE REVIEW

**Comment by lucaferranti** [comment]
the issue was with a bug with how `>` is defined in IA v0.2

**Comment by schillic** [comment]
Can we test this somehow?

File: src/branchandbound.jl [hunk 1]
```diff
@@ -43,10 +43,10 @@ function _monotonicity_check(f::Function, X::IntervalBox{N}, ∇fX::AbstractVect
     high = zeros(eltype(X), N)
 
     @inbounds for (i, di) in enumerate(∇fX)
-        if di >= 0  #  increasing
+        if inf(di) >= 0  #  increasing
             high[i] = interval(sup(X[i]))
             low[i] = interval(inf(X[i]))
-        elseif di <= 0  # decreasing
+        elseif sup(di) <=0  # decreasing
```
Comment (schillic) [inline src/branchandbound.jl:49]:
```suggestion
        elseif sup(di) <= 0  # decreasing
```

**Review by schillic — APPROVED** [review]
